<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Version>1.3.1</Version>
    <Description>A BSV bitcoin blockchain parser (also works for BTC and BCH).

Ver 1.3.1 updates library references to Newtonsoft.Json v13.0.4 and NBitcoin v10.0.3.
Ver 1.3.0 adds blockLength and blockchainFilename.
Ver 1.2.9 renames the block class name avoid name collision.
Ver 1.2.8 adds support for segwit blocks.
Ver 1.2.7.1 adds a nextNblockDataFiles parameter for BlockchainParser class. The next N blockdata files would be processed if N is assign a value. The default value is int.MaxValue.
Ver 1.2.6. This is a fork of BitcoinBlockChain (Author: Ladislau Molnar).
Version check is disabled.
Stylecop requirement is removed.

BitcoinSV. 
BSV.</Description>
    <PackageReleaseNotes>Ver 1.3.1 updates library references to Newtonsoft.Json v13.0.4 and NBitcoin v10.0.3.</PackageReleaseNotes>
    <Copyright></Copyright>
    <PackageLicenseFile></PackageLicenseFile>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageProjectUrl>https://github.com/wy000000/BsvBitcoinBlockChain</PackageProjectUrl>
    <AssemblyVersion>1.3.1.0</AssemblyVersion>
    <FileVersion>1.3.1.0</FileVersion>
    <Authors>wy</Authors>
    <Company />
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/wy000000/BsvBitcoinBlockChain</RepositoryUrl>
    <RepositoryType>https://github.com/wy000000/BsvBitcoinBlockChain.git</RepositoryType>
    <Title>BsvBitcoinBlockChain</Title>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Data\BlockHeader.cs" />
    <Compile Remove="Data\Transaction.cs" />
    <Compile Remove="Data\TransactionInput.cs" />
    <Compile Remove="Data\TransactionOutput.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NBitcoin" Version="10.0.3" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
